apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-access
  namespace: argo-events
spec:
  encryptedData:
    token: AgBi7Z4WBshsGtPcUIpjzzc4yNxZCo5vKudVrX+IAKLIjWD/mVfZhPypT3oqztlwpm4NCgrSAL4ha4o/b5uj+BW/XpGB8lPBVt7BvnVB2nZQFoBBvAAz5/RlJy5zgYXIZiew9ooveaQGCbyTs/e6Dt9QgA8L3wTawvkBrJl6rNsrcfAgI+MX67/sDR98tLPNDXXcW8+0fhUDg/bRxohHjUXQuCpwIr6LcxyDa0WLNdd/m2sKn7GnWim47vlZy3k9rsvcqOykoFVKqM326im6qdn2VNbyIckGBHMZLhoeptFvbeZKhQwvSI/Ca+sbg6oYNeNiwhdDzMZkM8vMuDUPJxPElwJNpMfg9jcRfHulGPUwSjqE99ouhREiMHR8OSGCYeVPm73uwkRbmqgwDORFfB9XY61lKMMUanG47QdWBB+EoI+XobJH+mmjL8x7uqESBDlFBtJw/x4Lq5GuF76XbzJffbTZBOPTJ5VJlsPkGIVKjadIWW0zd6FgXxh1B119uPII23ZQj+tzRMJu4XBpw3wCCTg3WDM3/OGPCm9A3AfrnVY4mbXOr87N98+hazE0gKhSTW3GtB8EUrYnH3y6o5Tu4hs/edy8KJJqLIRFA43hI5DEOvPohc+++NoisKW0pp9gS398R8CtcuCVQNhzE76dUxAL+LWLeiqI6YbZKV6QJAGwa0OaZmGPuLSexqop1zmV3/6TzmgQrgVJGCGDcmWzPZRpEITURl7nrq6ItxqjJqoXZPyqwn1L
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: github-access
      namespace: argo-events
    type: Opaque

